In [47]:
import torch
import numpy as np
torch.manual_seed(7)

In [48]:
features = torch.randn(1, 3) # 1x3
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [49]:
n_input = features.shape[1] #3
n_hidden = 2 # 2 hiddern unit
n_out = 1

In [50]:
W1 = torch.randn(n_input, n_hidden) #W1: 3x2 --> beacuse, features: 1x3, and 2 hidden unit
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [51]:
W2 = torch.randn(n_hidden, n_out) #W2: 2x1 --> beacuse, previous step output 1x2, and final output=1
W2

tensor([[-1.6822],
        [ 0.3177]])

In [52]:
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_out)

In [53]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [54]:
h = activation(torch.mm(features, W1) + B1)

In [55]:
output = activation(torch.mm(h, W2) + B2)

In [56]:
output

tensor([[ 0.3171]])